replica0: ./target/release/script 0
replica1: ./target/release/script 1
replica2: ./target/release/script 2
replica3: ./target/release/script 3
replica4: ./target/release/script 4
replica5: ./target/release/script 5
replica6: ./target/release/script 6
replica7: ./target/release/script 7
replica8: ./target/release/script 8
replica9: ./target/release/script 9
replica10: ./target/release/script 10
replica11: ./target/release/script 11
replica12: ./target/release/script 12
replica13: ./target/release/script 13
replica14: ./target/release/script 14
replica15: ./target/release/script 15
replica16: ./target/release/script 16
replica17: ./target/release/script 17
replica18: ./target/release/script 18
replica19: ./target/release/script 19